version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: yonework_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    networks:
      - yonework_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    labels:
      - "com.yonework.service=redis"
      - "com.yonework.environment=${ENV:-development}"

  prometheus:
    image: prom/prometheus:latest
    container_name: yonework_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=15d'
      - '--storage.tsdb.retention.size=512MB'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    networks:
      - yonework_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    labels:
      - "com.yonework.service=prometheus"
      - "com.yonework.environment=${ENV:-development}"

  alertmanager:
    image: prom/alertmanager:latest
    container_name: yonework_alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=${ALERTMANAGER_EXTERNAL_URL:-http://localhost:9093}'
    networks:
      - yonework_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9093/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    labels:
      - "com.yonework.service=alertmanager"
      - "com.yonework.environment=${ENV:-development}"

volumes:
  redis_data:
    driver: local
    driver_opts:
      type: none
      device: ${REDIS_DATA_PATH:-./data/redis}
      o: bind
  prometheus_data:
    driver: local
    driver_opts:
      type: none
      device: ${PROMETHEUS_DATA_PATH:-./data/prometheus}
      o: bind

networks:
  yonework_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: yonework_net
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
    labels:
      - "com.yonework.environment=${ENV:-development}"